name       : gtkd
version    : 3.10.0
release    : 27
source     :
    - https://github.com/gtkd-developers/GtkD/archive/refs/tags/v3.10.0.tar.gz : 5c6edcdcfb6160ffc1524ab4996471e608c3632d81bd8ea689cf0e52ed13e953
license    : LGPL-3.0-or-later
component  : desktop.gtk
summary    : GtkD is a D binding and OO wrapper of GTK+
description: |
    GtkD is the Digital Mars D programming language OO wrapper for Gtk+ 3.22
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(gtksourceview-4)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(vte-2.91)
    - ldc
make       : |
    %make DC="ldc"
install    : |
    unset LDFLAGS
    %make_install prefix=/usr libdir=lib%LIBSUFFIX% \
      install-shared-gstreamer install-headers-gstreamer \
      install-shared-gtkd install-headers-gtkd \
      install-shared-gtkdgl install-headers-gtkdgl \
      install-shared-gtkdsv install-headers-gtkdsv \
      install-shared-peas install-headers-peas \
      install-shared-vte install-headers-vte
