name       : gtkd
version    : 3.7.5
release    : 3
source     :
    - https://github.com/gtkd-developers/GtkD/archive/v3.7.5.tar.gz : 9882ebae0ccdca7dc5850842bf547bec2cbdfa6f1b87909f84f20c59ac9da5c1
license    : LGPL-3.0
component  : desktop.gtk
summary    : GtkD is a D binding and OO wrapper of GTK+
description: |
    GtkD is the Digital Mars D programming language OO wrapper for Gtk+ 3.22
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkglext-1.0)
    - dmd
build      : |
    unset LDFLAGS
    %make DC=dmd prefix=/usr libdir=lib%LIBSUFFIX% \
      shared-gstreamer \
      shared-gtkd \
      shared-gtkdgl \
      shared-peas \
      shared-sv \
      shared-vte
install    : |
    %make_install DC=dmd prefix=/usr libdir=lib%LIBSUFFIX% \
      install-shared-gstreamer install-headers-gstreamer \
      install-shared-gtkd install-headers-gtkd \
      install-shared-gtkdgl install-headers-gtkdgl \
      install-shared-gtkdsv install-headers-gtkdsv \
      install-shared-peas install-headers-peas \
      install-shared-vte install-headers-vte
