name       : gtkd
version    : 3.8.3
release    : 8
source     :
    - https://github.com/gtkd-developers/GtkD/archive/v3.8.3.tar.gz : 7e0b2a10a4908b183ba842d54e9b1dc0761dcf316b65766f430010fe3bb95593
license    : LGPL-3.0-or-later
component  : desktop.gtk
summary    : GtkD is a D binding and OO wrapper of GTK+
description: |
    GtkD is the Digital Mars D programming language OO wrapper for Gtk+ 3.22
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkglext-1.0)
    - ldc
build      : |
    unset LDFLAGS
    %make prefix=/usr libdir=lib%LIBSUFFIX% \
      shared-gstreamer \
      shared-gtkd \
      shared-gtkdgl \
      shared-peas \
      shared-sv \
      shared-vte
install    : |
    %make_install prefix=/usr libdir=lib%LIBSUFFIX% \
      install-shared-gstreamer install-headers-gstreamer \
      install-shared-gtkd install-headers-gtkd \
      install-shared-gtkdgl install-headers-gtkdgl \
      install-shared-gtkdsv install-headers-gtkdsv \
      install-shared-peas install-headers-peas \
      install-shared-vte install-headers-vte
